# Generated by Django 4.2.10 on 2026-02-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lostfound', '0002_lostitem_claimed_by_alter_lostitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='claim_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
