# Generated by Django 4.2.10 on 2026-03-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('parent_phone', models.CharField(max_length=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('tutor_approved', 'Tutor Approved'), ('hod_approved', 'HOD Approved'), ('deputy_approved', 'Deputy Warden Approved'), ('warden_approved', 'Associate Warden Approved'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associate_warden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_warden', to=settings.AUTH_USER_MODEL)),
                ('deputy_warden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_deputy', to=settings.AUTH_USER_MODEL)),
                ('hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hod', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
