# Generated by Django 4.2.10 on 2026-03-08 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='confirm_with',
            field=models.CharField(default='Father', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='associate_warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_warden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='deputy_warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_deputy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
