# Generated by Django 4.2.10 on 2026-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('cse', 'CSE'), ('ece', 'ECE'), ('eee', 'EEE'), ('mech', 'MECH'), ('it', 'IT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('hod', 'HOD'), ('deputy_warden', 'Deputy Warden'), ('associate_warden', 'Associate Warden'), ('principal', 'Principal'), ('admin', 'Admin')], max_length=50),
        ),
    ]
