# Generated by Django 4.2.10 on 2026-03-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outpass',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
