# Generated by Django 4.2.10 on 2026-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
