# Generated by Django 4.2.10 on 2026-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('hostel', 'Hostel'), ('transport', 'Transport'), ('infrastructure', 'Infrastructure'), ('ragging', 'Ragging'), ('other', 'Other')], default='academic', max_length=50),
        ),
    ]
