# Generated by Django 4.2.10 on 2026-03-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('normal', 'Normal Complaint'), ('anonymous', 'Anonymous Complaint'), ('confidential', 'Confidential (Principal Only)')], default='normal', max_length=20),
        ),
    ]
