# Generated by Django 4.2.10 on 2026-03-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='section',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
